#! /bin/bash

ifconfig eth0 $1 netmask $2 2>> ipErrorMessages.tmp

gatewayCheck=`ip route | grep "default" | tr -s " " | cut -d " " -f3 |  tr -d "\n\r"`
if [ -z $gatewayCheck ]; then
	# when default route not exists!
	ip route add default dev eth0 via $3 2>> gwErrorMessages.tmp
else
	# when default route exists but must change!
	ip route replace default dev eth0 via $3 2>> gwErrorMessages.tmp
fi

if [ -s ipErrorMessages.tmp ] || [ -s gwErrorMessages.tmp ]; then
	head -n 1 ipErrorMessages.tmp >&2
	head -n 1 gwErrorMessages.tmp >&2
	rm  ipErrorMessages.tmp
	rm  gwErrorMessages.tmp
	exit 2
else
	exit 0
fi